### PR TITLE
MWAR-422 - Attach artifacts with classifier as primary if requested

### PR DESCRIPTION
**Pull request by bondolo**
Following this checklist to help us incorporate your contribution quickly and easily:

 - [X] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MWAR) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [X] Each commit in the pull request should have a meaningful subject line and body.
 - [X] Format the pull request title like `[MWAR-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MWAR-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [X] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.
 - [X] You have run the integration tests successfully (`mvn -Prun-its clean verify`).

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

Completed contributors agreement for other projects (netbeans)

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [X] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [x] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

 Completed (via NetBeans)

### CODE REVIEW

**Comment by bondolo** [comment]
If the primary artifact flag is true then the artifact is attached as the primary artifact even if a classifier is used. I also added debug logs to the three attachment conditions to make it clearer what is being done.

**Comment by bondolo** [comment]
Is anyone monitoring these pull requests???

**Comment by rfscholte** [comment]
Closing as described in https://issues.apache.org/jira/browse/MWAR-422

**Comment by jira-importer** [comment]
Resolve #487

**Pull request closed without merging**
