### PR TITLE
Avoid resource leak from class loader

### PR DESCRIPTION
**Pull request by elharo**
@hboutemy

### CODE REVIEW

**Comment by michael-o** [comment]
What about try-with-resources?

**Comment by elharo** [comment]
ClassLoader does not implement AutoCloseable. I don't know why, but it doesn't.

**Comment by pzygielo** [comment]
> ClassLoader does not implement AutoCloseable. I don't know why, but it doesn't.

But URLClassLoader does.

**Comment by elharo** [comment]
There's something weird about this though: Unhandled exception type IOException thrown by automatic close() invocation on loader

**Comment by pzygielo** [comment]
> There's something weird about this though: Unhandled exception type IOException thrown by automatic close() invocation on loader

Not weirder than using try-with-resources with `FileOutputStream` I guess.

**Comment by elharo** [comment]
Let me try to be clearer; try with resources does not work here. I tried it. It did not work.

**Comment by rmannibucau** [comment]
try/with/resource should work - we did something close in tomee - but I think the classloader should be drop to quit fast the previous loop. Idea is to iterate over classpathElements and if it is a jar (endsWith(".jar") should be more than enough since folders will likely not contain these classes for a war project) then open it with JarFile and check it has one of the two entries tested - hitting zip dictionary so fast. Will likely avoid to go through all the classpath (often the API are at the beginning of deps) and save to create a ton of JarLoaders for nothing.

**Pull request merged**
