### PR TITLE
[MWAR-430] Discover Jakarta Servlet API as excuse for not having web.xml

### PR DESCRIPTION
**Pull request by pzygielo**
@olamy may I ask for review, please?

### CODE REVIEW

**Comment by khmarbaise** [comment]
@olamy WDYT?

**Comment by pzygielo** [comment]
@khmarbaise - commits squashed

**Comment by pzygielo** [comment]
1. so it seems that (failed) :red_circle: [build 1](https://builds.apache.org/job/maven-box/job/maven-war-plugin/job/pzygielo-mwar-430/1/) ran against 4 commits (it should not matter as contents is the same)
2. I executed `verify -P run-its` (before push) locally on linux/jdk8 and as on Jenkins - it's ok in my env
3. on first read of [1/consoleFull](https://builds.apache.org/job/maven-box/job/maven-war-plugin/job/pzygielo-mwar-430/1/consoleFull) failure is not obvious for me.
I suspected that new class from jakarta
```
$ file WebServlet.class 
WebServlet.class: compiled Java class data, version 52.0 (Java 1.8)
```
could not collaborate with JDK7.:
```
Caused by: java.lang.UnsupportedClassVersionError: jakarta/servlet/annotation/WebServlet : Unsupported major.minor version 52.0
...
    at org.apache.maven.plugins.war.WarMojo.hasClassInClasspath (WarMojo.java:341)
```
but a lot more ITs fail with JDK7, not new one only, so I'm a bit confused...

**Comment by pzygielo** [comment]
In [blue ocean/pipeline](https://builds.apache.org/blue/organizations/jenkins/maven-box%2Fmaven-war-plugin/detail/pzygielo-mwar-430/1/pipeline) view it's clear that JDK7 is common factor.

**Comment by hboutemy** [comment]
if the new IT requires Java 8, you can mark it with invoker.properties
see for example https://github.com/apache/maven-pmd-plugin/blob/master/src/it/MPMD-302-JDK14/invoker.properties

**Comment by pzygielo** [comment]
> if the new IT requires Java 8, you can mark it with invoker.properties
> see for example https://github.com/apache/maven-pmd-plugin/blob/master/src/it/MPMD-302-JDK14/invoker.properties

Thanks, that's what I did in #9.

**Comment by pzygielo** [comment]
@hboutemy - but with your confirmation that it's the way to go I'll squash #9 here and push new commit for review.

**Comment by hboutemy** [comment]
IMHO, no need for UnsupportedClassVersionError check: this won't happen for end-users
limiting the execution of the IT to 8+ JDK versions is sufficient

**Comment by pzygielo** [comment]
> IMHO, no need for UnsupportedClassVersionError check: this won't happen for end-users
limiting the execution of the IT to 8+ JDK versions is sufficient.

Just to clarify my understanding: if there is jakarta's web servlet annotation in CP (only then plugin would load this class), it means also that project is already compiled with JDK8+. Right? In such case, catching UCVE isn't needed indeed!

**Comment by jira-importer** [comment]
Resolve #495

**Pull request merged**
